set -sg escape-time 10
set -g mouse on
set -g set-clipboard on

set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# vim settings
# # Enable vi mode keys
set-window-option -g mode-keys vi

# Use v to trigger selection matching Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
